spring.application.name=Auth


spring.datasource.url=jdbc:postgresql://localhost:5432/authdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update

jwt.secret=123@1212#^^^&&$###
jwt.expiration=3600000